status: draft! not used yet
dataPath: ./data
port: 8080
identifyingField: uuid
defaultSearchField: content

  # we can also put the field config in the input data
  # just get the generic config options here
  # and do check the input data on some constraints (identifying and default field for instance)

# we do want to specify the output fields