
// https://lucene.apache.org/core/10_0_0/queryparser/org/apache/lucene/queryparser/flexible/standard/nodes/intervalfn/package-summary.html
// https://lucene.apache.org/core/10_2_2/queryparser/org/apache/lucene/queryparser/flexible/standard/StandardQueryParser.html

PUT http://localhost:8080/query HTTP/1.1
Content-Type: "application/json"

{
    "pagesize": 2,
    //"query": "person00001",

    //"query": "fn:containedBy(Anthonij fn:phrase(Axel Anthonij Rosenquest))",
   // "query": "fn:containedBy(anthonij person00001)",

    //"query": "fn:fuzzyTerm(anthonij 2 1000)",

     "query": "[Ant TO Anthonij]",
    // "query": "fn:wildcard(paard*)",

    // "query": "\"person00001 concept00001\"~115",
    // "query": "\"balinees batavia\"~100",
    // "query": "fn:maxgaps(10 fn:ordered(radja batavia))",

    "facetpagesize": 10,
    "facetfilters": []
}