
PUT http://localhost:8080/query HTTP/1.1
Content-Type: "application/json"

{
    //"query": "fn:fuzzyTerm(anthonij 2 1000)",   
    // "query": "fn:wildcard(paard*)",
    // "query": "fn:maxgaps(10 fn:ordered(radja batavia))",
}