// https://lucene.apache.org/core/10_0_0/queryparser/org/apache/lucene/queryparser/flexible/standard/nodes/intervalfn/package-summary.html
// https://lucene.apache.org/core/10_2_2/queryparser/org/apache/lucene/queryparser/flexible/standard/StandardQueryParser.html

PUT http://localhost:8080/query HTTP/1.1
Content-Type: "application/json"

{
    "pagesize": 8,
    "passagesize": 2,
    
    //"query": "batavia",
    //"query": "tag_timespan",
    //"query": "tag_person",
    // "query": "\"tag_person anthonij\"~5",
    // "query": "batavia fn:containedBy(tag_person anthonij)",

    "facets": [
        //{"dimension": "ead", "filters": []}
        //{"dimension": "ead", "filters": [["a", "b", "c"]]}
    ],

    "fields": [
        {
        "name": "identifier",
        "type": "string"
        },
        {
        "name": "name",
        "type": "string"
        },
        {
        "name": "title",
        "type": "string"
        },
        {
        "name": "inventorynumber",
        "type": "string"
        }
    ]
}