// https://lucene.apache.org/core/10_0_0/queryparser/org/apache/lucene/queryparser/flexible/standard/nodes/intervalfn/package-summary.html
// https://lucene.apache.org/core/10_2_2/queryparser/org/apache/lucene/queryparser/flexible/standard/StandardQueryParser.html

PUT http://localhost:8080/query HTTP/1.1
Content-Type: "application/json"

{
    "pagesize": 4,
    "passagesize": 1,
    
    //"query": "batavia",
    //"query": "tag_timespan",
    // "query": "tag_person",

    //"query": "\"tag_person anthonij\"~1",
    // "query": "\"tag_person anthonij\"~0",
    
    //"query": "batavi*",
    //"query": "fn:ordered(ian gerhard hof)",

    "query": "fn:containedBy(tag_person anthonij) AND fn:containedBy(tag_place batavia)",


    // "query": "batavia fn:containedBy(tag_person anthonij)",
    // "query": "inventorynumber:[1054 TO 1067]",
    // "query": "[Ant TO Anthonij]",

    "facets": [
        //{"dimension": "ead", "filters": []}
        //{"dimension": "ead", "filters": [["a", "b", "c"]]}
    ],

    "fields": [
        {
        "name": "identifier",
        "type": "string"
        },
        {
        "name": "name",
        "type": "string"
        },
        {
        "name": "title",
        "type": "string"
        },
        {
        "name": "inventorynumber",
        "type": "string"
        }
    ]
}